### ISSUE TITLE
The 3rd International Epigenomics Conference | Rongxin's Blog

### ISSUE THREAD

**Issue by rongxinzh** [rongxinzh/rongxinzh.github.io#4]
https://rongxinzh.github.io/2019/10/27/The-3rd-International-Epigenomics-Conference/#more 

 &nbsp;刚怀着崇敬的心情去上海参加完第三届国际表观遗传学研讨会，之前导师在微信上发给我这个会议通知的时候，我稍微犹豫了一下，因为虽然我的大方向是表观遗传信息学，但是我目前主要做的还是核酸二级结构，可是，当我看到Bing Ren教授也要做报告的时候，就毅然决然的注册了，那可是我的偶像啊，一个经常在CNS级别论文

**Comment by supersupersun** [comment]
老铁双击666

**Comment by rongxinzh** [comment]
> @supersupersun
> 老铁双击666

##### 你是first blood.
